#!/bin/bash

######################
# BigLinux Iso Generator
# by Bruno Gonçalves Araujo <bigbruno@gmail.com>
# licensed under GPLv2 or greater.
# released in 07/10/2015


# Forma de uso
# $1 pasta de trabalho
# $2 tipo de compactacao xz ou gzip
# $3 nome de identificacao do iso
# Exemplo: sudo /usr/share/biglinux/iso-generator/makesquashfs.sh "/home/bruno/remaster/iso32bits" "gzip" "BigLinux 14.04 final"


cd "$1"

# Kernel e initrd para o livecd
mkdir -p image/live
rm -f remaster/chroot/boot/*old-dkms*

# fix keyboard

echo '# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"' > remaster/chroot/etc/default/keyboard

rm -f remaster/chroot/etc/hostname

cp -f $(find remaster/chroot/boot/ -name vmlinuz* |  tail -1) image/live/vmlinuz
cp -f $(find remaster/chroot/boot/ -name initrd.img* |  tail -1) image/live/initrd.lz

# Gera o manifest
chroot remaster/chroot dpkg-query -W --showformat='${Package} ${Version}\n' | sudo tee image/live/filesystem.manifest
cp -v image/live/filesystem.manifest image/live/filesystem.manifest-desktop
REMOVE='ubiquity biglinux-install-desktop-icon ubiquity-frontend-gtk ubiquity-frontend-kde live lupin-live live-initramfs deepin-installer'



live-boot live-config live-config-systemd

for i in $REMOVE 
do
        sed -i "/${i}/d" image/live/filesystem.manifest-desktop
done

/usr/share/biglinux/iso-generator/chroot-off.sh "$1" 2> /dev/null
/usr/share/biglinux/iso-generator/chroot-off.sh "$1" 2> /dev/null
/usr/share/biglinux/iso-generator/chroot-off.sh "$1" 2> /dev/null

# Gera o squashfs
#gzip
if [ "$2" = "gzip" ]; then
    rm -f remaster/chroot/apt_errors*.txt
    rm -f image/live/filesystem.squashfs
    mksquashfs remaster/chroot image/live/filesystem.squashfs
fi


#xz
if [ "$2" = "xz" ]; then
    rm -f remaster/chroot/apt_errors*.txt
    rm -f image/live/filesystem.squashfs
    mksquashfs remaster/chroot image/live/filesystem.squashfs -comp xz -Xbcj x86 -no-xattrs -always-use-fragments -b 32768  -Xdict-size 100%
fi


printf $(du -sx --block-size=1 remaster/chroot | cut -f1) > image/live/filesystem.size


touch image/ubuntu
mkdir image/.disk
cd image/.disk
touch base_installable
echo "full_cd/single" > cd_type
echo "$3" > info
echo "Remaster generated by BigLinux Iso Generator - https://www.biglinux.com.br" > release_notes_url
cd ../../
